name: feature_source_firebase
description: Feature source integration with Firebase Remote Config.
version: 1.1.0
repository: https://github.com/nogipx/feature

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  meta: ^1.7.0
  feature_core: ^1.1.0
  firebase_remote_config: ^4.2.3

dependency_overrides:
  feature_core:
    path: ../feature_core

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
