name: feature_source_firebase
description: Plugin for feature_core. 
  Implements Firebase Remote Config as feature provider.
version: 1.2.0
repository: https://github.com/nogipx/feature

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  feature_core: ^1.2.0
  firebase_remote_config: ^4.2.3
  meta: ^1.7.0

#dependency_overrides:
#  feature_core:
#    path: ../feature_core

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
