name: feature_flutter
description: Flutter package for convenient use of feature flags. 
  Designed for use with feature_core package.
version: 2.0.0
repository: https://github.com/nogipx/feature

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  feature_core: ^1.2.0
  flutter:
    sdk: flutter

dependency_overrides:
  feature_core:
    path: ../feature_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: