name: feature_core
description: Core classes and contracts for managing features.
version: 1.0.2
repository: https://github.com/nogipx/feature

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  data_manage: ^1.2.2
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.24.3
  mocktail: ^0.3.0
