name: feature_core
description: Dart package for flexible retrieving and managing feature flags.
version: 1.2.0
repository: https://github.com/nogipx/feature

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  rxdart: ^0.27.3
  meta: ^1.7.0
  logging: ^1.2.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.24.3
  mocktail: ^0.3.0
